### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by MAdil45** [flaviostutz/sentinelloader#21]
I am trying to install via using 'Pip install sentinelloader". However, I am continuously coming across this error. I have tried downgrading python, try installing Gdal separately but couldn't success. Could please anyone if look into this and provide some feedback regarding the solution. Thanks
![Screenshot from 2022-08-24 22-06-07](https://user-images.githubusercontent.com/36837450/186479892-8d6406b4-6850-4221-b369-6e591cc6969f.png)

**Comment by MAdil45** [comment]
Never mind. I have installed it. There was a problem with gdal.

**Comment by quillaja** [comment]
@MAdil45 
> Never mind. I have installed it. There was a problem with gdal.

What did you do to solve this issue? I'm having a similar issue with gdal, even though I just installed the VS2022 C++ build tools.

```
...
      copying gdal-utils\osgeo_utils\samples\__init__.py -> build\lib.win-amd64-cpython-311\osgeo_utils\samples
      running build_ext
      building 'osgeo._gdal' extension
      building 'osgeo._osr' extension
      building 'osgeo._ogr' extension
      building 'osgeo._gdalconst' extension
      building 'osgeo._gnm' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gdal
Failed to build gdal
ERROR: Could not build wheels for gdal, which is required to install pyproject.toml-based projects
```

**Comment by MAdil45** [comment]
@quillaja Try:
conda install conda-forge gdal

Then install libstdc++ in Conda Environment by using:
conda install -c conda-forge libstdcxx-ng

It worked for me
