### ISSUE TITLE
Docker Usage Sample

### ISSUE THREAD

**Issue by webmap2015** [flaviostutz/sentinelloader#5]
Hi, I want to run this project on docker image.

When I run "docker-compose up",  it give error "ERROR: Couldn't find env file: /home/User/sentinelloader/.env"

I decided to run with Dockerfile "docker build -t flaviostutz/sentinelloader ." and it created docker image.

So, I need a command sample to run this project on docker image for downloading "Level 1C tci.jp2".

Could you help ?

Thanks.

**Comment by flaviostutz** [comment]
Hi, @webmap2015! I've just updated README with instructions for running sentinelloader with containers. Could you please test it?

**Comment by webmap2015** [comment]
It's working good.

Thanks.
