### ISSUE TITLE
Error processing the downloaded tile

### ISSUE THREAD

**Issue by VJ-sts** [flaviostutz/sentinelloader#6]
Hi 
I am trying to execute the sentinelloader python example.
I could able to download the 60m data. But in processing, I am getting the following error. For your info I have already installed gdal.

DEBUG:sentinelloader:Removing near black compression artifacts
INFO:sentinelloader:Couldn't get data for 2020-01-01 using the specified filter. err=gdal nearblack utility was not found in the system. install it

**Comment by flaviostutz** [comment]
It seems like the nearblack utility is not being distributed along with newer gdal releases. Try to use the container provided in readme. It has the nearblack utility embedded to the image.

Please tell me if you solved your problem :)

**Comment by VJ-sts** [comment]
I am managed to pull the container using docker windows toolbox and run the docker-compose.yml. All the files are downloaded and sentinelloader was created successfully.
But I couldn't access the  http://localhost:8686/   I am unable to connect the network I have enabled IIS windows features and also tried to change the VMware network setting in port forwarding.
Where you think I went wrong. Or anyother method I should follow
Thanks

**Comment by flaviostutz** [comment]
Are you using VMWare? What OS are you using in your host and what OS on VMWare?

**Comment by VJ-sts** [comment]
Yes it is OracleVM. Host is windows and in the VM it is Linux.

**Comment by flaviostutz** [comment]
What was the exact content of the docker-compose.yml you ran?

**Comment by VJ-sts** [comment]
The one given in Readme

I changed the Copernicus user name and password with my Copernicus credentials

version: '3.3' services: sentinelloader: image: flaviostutz/sentinelloader environment: - COPERNICUS_USER=my Copernicus user - COPERNICUS_PASSWORD=my Copernicus password ports: - 8686:8888

**Comment by VJ-sts** [comment]
Hi Flavio
I have sorted the issue. I accessed the container in Kitmatic (Docler control) application and executed the code now it is working fine. What version of GDAL you are using the one has this nearblack utility?

Thanks
